name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Drustcraft Network (Azentina)
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.AZENTINA_HOST }}
          username: ${{ secrets.AZENTINA_USER }}
          password: ${{ secrets.AZENTINA_PASSWORD }}
          server-dir: plugins/
          exclude:
            - **/*.md
            - **/.git*
            - **/.git*/**
