name: Drustcraft Network Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  network-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Sync Azentina
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          server: ${{ secrets.AZENTINA_HOST }}
          username: ${{ secrets.AZENTINA_USER }}
          password: ${{ secrets.AZENTINA_PASSWORD }}
          server-dir: plugins/
          exclude: '[**/*.md, **/.git*, **/.git*/**, LICENSE]'
